# Generated by Django 3.2.8 on 2021-11-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(default='Eng', to='catalog.Language'),
        ),
    ]
