# Generated by Django 3.2.8 on 2021-12-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, choices=[('Eng', 'English'), ('Chi', 'chinese'), ('Hin', 'Hindi'), ('Spa', 'Spanish')], max_length=3),
        ),
    ]
